import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuthStore } from '../store/auth';
export default function AdminPage() {
    const { isAdmin } = useAuthStore();
    if (!isAdmin()) {
        return (_jsx("div", { className: "bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded", children: "You do not have admin access" }));
    }
    return (_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold mb-8", children: "Administration" }), _jsxs("div", { className: "grid grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h2", { className: "text-xl font-bold mb-4", children: "Users" }), _jsx("p", { className: "text-gray-500 mb-4", children: "Manage organization users" }), _jsx("button", { className: "px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "Manage Users" })] }), _jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h2", { className: "text-xl font-bold mb-4", children: "Departments" }), _jsx("p", { className: "text-gray-500 mb-4", children: "Manage departments" }), _jsx("button", { className: "px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "Manage Departments" })] }), _jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h2", { className: "text-xl font-bold mb-4", children: "Categories" }), _jsx("p", { className: "text-gray-500 mb-4", children: "Manage memo categories" }), _jsx("button", { className: "px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "Manage Categories" })] }), _jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h2", { className: "text-xl font-bold mb-4", children: "Reports" }), _jsx("p", { className: "text-gray-500 mb-4", children: "View system statistics" }), _jsx("button", { className: "px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "View Reports" })] })] })] }));
}
